from setuptools import setup, find_packages

setup(
    name="cisd",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "pandas",
        "scipy",
        "scikit-learn",
        "tensorflow>=2.4.0",
        "torch>=1.8.0",
        "matplotlib",
        "seaborn",
        "econml",
        "causalml",
        "dowhy",
        "pyro-ppl",
        "networkx",
    ],
    extras_require={
        "spatial": [
            "geopandas",
            "shapely",
            "libpysal",
            "esda",
            "spreg",
            "statsmodels",
        ],
        "viz": [
            "contextily",
            "folium",
        ],
        "all": [
            "geopandas",
            "shapely",
            "libpysal",
            "esda",
            "spreg",
            "statsmodels",
            "contextily",
            "folium",
            "osmnx",
            "ipywidgets",
        ],
    },
    author="Amir Rafe",
    author_email="amir.rafe@usu.edu",
    description="Causal-Intervention Scenario Design (CISD) framework for active transportation research",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/amirraf/CausalAT-CISD",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering",
    ],
    python_requires=">=3.7",
)
